// Mock regions
export const mockRegions = ["North Region", "South Region", "East Region", "West Region", "Central Region"]

// Mock agencies
export const mockAgencies = [
  "Highway Department",
  "Water Resources",
  "Public Buildings",
  "Parks & Recreation",
  "Transit Authority",
]

// Mock projects data
export const mockProjects = [
  {
    id: 1,
    name: "Main Street Bridge Replacement",
    description: "Replace aging bridge structure on Main Street",
    budget: 4500000,
    timeline: "2023-2025",
    status: "In Progress",
    region: "North Region",
    agency: "Highway Department",
  },
  {
    id: 2,
    name: "City Hall Renovation",
    description: "Modernize city hall facilities and improve accessibility",
    budget: 2800000,
    timeline: "2024-2025",
    status: "Planning",
    region: "Central Region",
    agency: "Public Buildings",
  },
  {
    id: 3,
    name: "Riverfront Park Development",
    description: "Create new recreational spaces along the riverfront",
    budget: 3200000,
    timeline: "2023-2024",
    status: "In Progress",
    region: "East Region",
    agency: "Parks & Recreation",
  },
  {
    id: 4,
    name: "Water Treatment Plant Upgrade",
    description: "Modernize water treatment facilities to improve capacity",
    budget: 7500000,
    timeline: "2022-2024",
    status: "In Progress",
    region: "West Region",
    agency: "Water Resources",
  },
  {
    id: 5,
    name: "Downtown Transit Hub",
    description: "Centralized transit center for bus and light rail connections",
    budget: 5200000,
    timeline: "2023-2026",
    status: "Planning",
    region: "Central Region",
    agency: "Transit Authority",
  },
  {
    id: 6,
    name: "Highway 101 Expansion",
    description: "Add additional lanes to Highway 101 between exits 10-15",
    budget: 8900000,
    timeline: "2022-2025",
    status: "In Progress",
    region: "South Region",
    agency: "Highway Department",
  },
  {
    id: 7,
    name: "Community Recreation Center",
    description: "Build new multi-purpose recreation facility",
    budget: 4100000,
    timeline: "2024-2025",
    status: "Planning",
    region: "North Region",
    agency: "Parks & Recreation",
  },
  {
    id: 8,
    name: "Stormwater Management System",
    description: "Upgrade drainage systems to prevent flooding in downtown area",
    budget: 3600000,
    timeline: "2023-2024",
    status: "In Progress",
    region: "East Region",
    agency: "Water Resources",
  },
  {
    id: 9,
    name: "County Courthouse Renovation",
    description: "Historical preservation and modernization of county courthouse",
    budget: 6200000,
    timeline: "2022-2024",
    status: "Completed",
    region: "Central Region",
    agency: "Public Buildings",
  },
  {
    id: 10,
    name: "Light Rail Extension",
    description: "Extend light rail service to northern suburbs",
    budget: 12500000,
    timeline: "2023-2027",
    status: "Planning",
    region: "North Region",
    agency: "Transit Authority",
  },
  {
    id: 11,
    name: "Coastal Highway Seawall",
    description: "Construct seawall to protect coastal highway from erosion",
    budget: 7800000,
    timeline: "2023-2025",
    status: "In Progress",
    region: "South Region",
    agency: "Highway Department",
  },
  {
    id: 12,
    name: "Municipal Airport Terminal",
    description: "Expand and modernize the municipal airport terminal",
    budget: 9400000,
    timeline: "2024-2026",
    status: "Planning",
    region: "West Region",
    agency: "Public Buildings",
  },
  {
    id: 13,
    name: "Downtown Revitalization",
    description: "Streetscape improvements and facade restoration in historic downtown",
    budget: 5100000,
    timeline: "2023-2025",
    status: "In Progress",
    region: "Central Region",
    agency: "Public Buildings",
  },
  {
    id: 14,
    name: "Regional Water Pipeline",
    description: "Install new water pipeline connecting northern communities",
    budget: 8300000,
    timeline: "2022-2024",
    status: "In Progress",
    region: "North Region",
    agency: "Water Resources",
  },
  {
    id: 15,
    name: "Sports Complex Expansion",
    description: "Add fields and facilities to existing sports complex",
    budget: 3900000,
    timeline: "2024-2025",
    status: "Planning",
    region: "East Region",
    agency: "Parks & Recreation",
  },
  {
    id: 16,
    name: "Bus Rapid Transit Corridor",
    description: "Dedicated bus lanes and stations along major east-west corridor",
    budget: 6700000,
    timeline: "2023-2025",
    status: "Planning",
    region: "West Region",
    agency: "Transit Authority",
  },
  {
    id: 17,
    name: "Emergency Operations Center",
    description: "Build new facility for emergency management and coordination",
    budget: 4800000,
    timeline: "2023-2024",
    status: "In Progress",
    region: "Central Region",
    agency: "Public Buildings",
  },
  {
    id: 18,
    name: "Mountain Pass Tunnel",
    description: "Construct tunnel through mountain to improve regional connectivity",
    budget: 15200000,
    timeline: "2023-2027",
    status: "Planning",
    region: "North Region",
    agency: "Highway Department",
  },
  {
    id: 19,
    name: "Wastewater Treatment Expansion",
    description: "Increase capacity of regional wastewater treatment plant",
    budget: 9100000,
    timeline: "2022-2025",
    status: "In Progress",
    region: "South Region",
    agency: "Water Resources",
  },
  {
    id: 20,
    name: "Greenway Trail Network",
    description: "Develop interconnected trail system throughout the region",
    budget: 4300000,
    timeline: "2023-2026",
    status: "Planning",
    region: "East Region",
    agency: "Parks & Recreation",
  },
]
